//
//  GlukloaderIcon.h
//  glukloader
//
//  Created by Alexandre Normand on 2014-07-27.
//  Copyright (c) 2014 Glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface GlukloaderIcon : NSObject

// Colors
+ (NSColor*)dropletColor;
+ (NSColor*)waveColor;
+ (NSColor*)waterColor;

// Generated Images
+ (NSImage*)imageOfIconWithIsConnected: (BOOL)isConnected isSyncInProgress: (BOOL)isSyncInProgress;

@end
