//
//  GlukloaderIcon.h
//  glukit
//
//  Created by Alexandre Normand on 2014-07-07.
//  Copyright (c) 2014 glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface GlukloaderIcon : NSObject

// Colors
+ (NSColor*)iconColor;
+ (NSColor*)dropletColor;
+ (NSColor*)waveColor;

// Drawing Methods
+ (void)drawIconWithSize: (CGFloat)size isConnected: (BOOL)isConnected isSyncInProgress: (BOOL)isSyncInProgress;

// Generated Images
+ (NSImage*)imageOfIconWithSize: (CGFloat)size isConnected: (BOOL)isConnected isSyncInProgress: (BOOL)isSyncInProgress;

@end
