//
//  GlukloaderIcon.h
//  glukit
//
//  Created by Alexandre Normand on 2014-05-09.
//  Copyright (c) 2014 glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface GlukloaderIcon : NSObject

// Colors
+ (NSColor*)color0;
+ (NSColor*)color2;

// Drawing Methods
+ (void)drawIconWithSize: (CGFloat)size;

// Generated Images
+ (NSImage*)imageOfIconWithSize: (CGFloat)size;

@end
