//
//  GlukloaderYosemite.h
//  Glukloader
//
//  Created by Alexandre Normand on 2014-11-13.
//  Copyright (c) 2014 Glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface GlukloaderYosemite : NSObject

// Colors
+ (NSColor*)color0;

// Generated Images
+ (NSImage*)imageOfGlukitIcon;

@end
