//
//  GlukloaderIcon.m
//  glukit
//
//  Created by Alexandre Normand on 2014-05-20.
//  Copyright (c) 2014 glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "GlukloaderIcon.h"


@implementation GlukloaderIcon

#pragma mark Cache

static NSColor* _iconColor = nil;
static NSColor* _dropletColor = nil;
static NSColor* _waveColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _iconColor = [NSColor colorWithCalibratedRed: 1 green: 0.825 blue: 0.71 alpha: 1];
    _dropletColor = [_iconColor shadowWithLevel: 0];
    _waveColor = [NSColor colorWithCalibratedHue: _iconColor.hueComponent saturation: 0.5 brightness: _iconColor.brightnessComponent alpha: _iconColor.alphaComponent];

}

#pragma mark Colors

+ (NSColor*)iconColor { return _iconColor; }
+ (NSColor*)dropletColor { return _dropletColor; }
+ (NSColor*)waveColor { return _waveColor; }

#pragma mark Drawing Methods

+ (void)drawIconWithSize: (CGFloat)size isConnected: (BOOL)isConnected isSyncInProgress: (BOOL)isSyncInProgress;
{
    //// General Declarations
    CGContextRef context = NSGraphicsContext.currentContext.graphicsPort;

    //// Color Declarations
    NSColor* syncDropletColor = [GlukloaderIcon.dropletColor highlightWithLevel: 0.3];
    NSColor* unconnectedDropletColor = [GlukloaderIcon.dropletColor highlightWithLevel: 1];
    NSColor* syncWaveColor = [GlukloaderIcon.waveColor highlightWithLevel: 0.3];
    NSColor* unconnectedWaveColor = [GlukloaderIcon.waveColor shadowWithLevel: 1];
    NSColor* outlineColor = [GlukloaderIcon.iconColor shadowWithLevel: 0.5];
    NSColor* syncOutlineColor = [outlineColor highlightWithLevel: 0.3];
    NSColor* unconnectedOutlineColor = [outlineColor shadowWithLevel: 0.5];

    //// Variable Declarations
    NSColor* calculatedWaveColor = isConnected && isSyncInProgress ? syncWaveColor : isConnected ? GlukloaderIcon.waveColor : unconnectedWaveColor;
    NSColor* calculatedDropletColor = isConnected && isSyncInProgress ? syncDropletColor : isConnected ? GlukloaderIcon.dropletColor : unconnectedDropletColor;
    NSColor* calculatedOutlineColor = isConnected && isSyncInProgress ? syncOutlineColor : isConnected ? outlineColor : unconnectedOutlineColor;

    //// Layer 3
    {
        [NSGraphicsContext saveGraphicsState];
        CGContextTranslateCTM(context, 4, -106);
        CGContextScaleCTM(context, 1.2, 1);



        //// Droplet Drawing
        NSBezierPath* dropletPath = NSBezierPath.bezierPath;
        [dropletPath moveToPoint: NSMakePoint(8.15, 116.64)];
        [dropletPath curveToPoint: NSMakePoint(6.98, 112.96) controlPoint1: NSMakePoint(8.12, 115.47) controlPoint2: NSMakePoint(7.34, 113.83)];
        [dropletPath curveToPoint: NSMakePoint(5.74, 106) controlPoint1: NSMakePoint(6.66, 112.21) controlPoint2: NSMakePoint(4.88, 106.8)];
        [dropletPath curveToPoint: NSMakePoint(0.25, 112.78) controlPoint1: NSMakePoint(5.68, 106.05) controlPoint2: NSMakePoint(1.83, 109.64)];
        [dropletPath lineToPoint: NSMakePoint(-0.03, 113.39)];
        [dropletPath curveToPoint: NSMakePoint(0.36, 120.5) controlPoint1: NSMakePoint(-0.31, 114) controlPoint2: NSMakePoint(-1.9, 117.74)];
        [dropletPath curveToPoint: NSMakePoint(4.1, 122) controlPoint1: NSMakePoint(1.35, 121.7) controlPoint2: NSMakePoint(2.43, 122)];
        [dropletPath curveToPoint: NSMakePoint(8.15, 116.64) controlPoint1: NSMakePoint(4.95, 122) controlPoint2: NSMakePoint(8.26, 121.08)];
        [dropletPath closePath];
        [dropletPath setMiterLimit: 4];
        [calculatedDropletColor setFill];
        [dropletPath fill];
        [calculatedOutlineColor setStroke];
        [dropletPath setLineWidth: 0.5];
        [dropletPath stroke];


        //// Wave Drawing
        NSBezierPath* wavePath = NSBezierPath.bezierPath;
        [wavePath moveToPoint: NSMakePoint(7.06, 116.13)];
        [wavePath curveToPoint: NSMakePoint(7.21, 116.12) controlPoint1: NSMakePoint(7.11, 116.13) controlPoint2: NSMakePoint(7.16, 116.13)];
        [wavePath curveToPoint: NSMakePoint(7.28, 116.12) controlPoint1: NSMakePoint(7.24, 116.12) controlPoint2: NSMakePoint(7.26, 116.12)];
        [wavePath curveToPoint: NSMakePoint(7.63, 116.11) controlPoint1: NSMakePoint(7.39, 116.12) controlPoint2: NSMakePoint(7.51, 116.11)];
        [wavePath curveToPoint: NSMakePoint(7.84, 116.03) controlPoint1: NSMakePoint(7.7, 116.09) controlPoint2: NSMakePoint(7.77, 116.07)];
        [wavePath curveToPoint: NSMakePoint(8, 115.89) controlPoint1: NSMakePoint(7.9, 116) controlPoint2: NSMakePoint(7.97, 115.96)];
        [wavePath curveToPoint: NSMakePoint(8.02, 115.86) controlPoint1: NSMakePoint(8.01, 115.88) controlPoint2: NSMakePoint(8.01, 115.87)];
        [wavePath lineToPoint: NSMakePoint(8.02, 115.84)];
        [wavePath curveToPoint: NSMakePoint(8.05, 115.97) controlPoint1: NSMakePoint(8.03, 115.88) controlPoint2: NSMakePoint(8.04, 115.93)];
        [wavePath curveToPoint: NSMakePoint(8.07, 116.05) controlPoint1: NSMakePoint(8.06, 116.01) controlPoint2: NSMakePoint(8.06, 116.03)];
        [wavePath lineToPoint: NSMakePoint(8.07, 116.05)];
        [wavePath curveToPoint: NSMakePoint(8.09, 116.05) controlPoint1: NSMakePoint(8.07, 116.05) controlPoint2: NSMakePoint(8.08, 116.05)];
        [wavePath curveToPoint: NSMakePoint(8.13, 117.28) controlPoint1: NSMakePoint(8.16, 116.45) controlPoint2: NSMakePoint(8.16, 116.87)];
        [wavePath curveToPoint: NSMakePoint(7.36, 119.9) controlPoint1: NSMakePoint(8.08, 118.22) controlPoint2: NSMakePoint(7.83, 119.14)];
        [wavePath curveToPoint: NSMakePoint(5.35, 121.62) controlPoint1: NSMakePoint(6.85, 120.71) controlPoint2: NSMakePoint(6.13, 121.29)];
        [wavePath curveToPoint: NSMakePoint(4.09, 121.93) controlPoint1: NSMakePoint(4.95, 121.79) controlPoint2: NSMakePoint(4.52, 121.93)];
        [wavePath curveToPoint: NSMakePoint(0.36, 120.43) controlPoint1: NSMakePoint(2.43, 121.93) controlPoint2: NSMakePoint(1.35, 121.63)];
        [wavePath curveToPoint: NSMakePoint(-0.66, 118.38) controlPoint1: NSMakePoint(-0.11, 119.86) controlPoint2: NSMakePoint(-0.47, 119.16)];
        [wavePath curveToPoint: NSMakePoint(-0.8, 116.16) controlPoint1: NSMakePoint(-0.84, 117.66) controlPoint2: NSMakePoint(-0.87, 116.9)];
        [wavePath curveToPoint: NSMakePoint(-0.83, 116.16) controlPoint1: NSMakePoint(-0.82, 116.16) controlPoint2: NSMakePoint(-0.83, 116.16)];
        [wavePath curveToPoint: NSMakePoint(-0.83, 116.15) controlPoint1: NSMakePoint(-0.83, 116.16) controlPoint2: NSMakePoint(-0.83, 116.15)];
        [wavePath curveToPoint: NSMakePoint(-0.79, 116.15) controlPoint1: NSMakePoint(-0.82, 116.15) controlPoint2: NSMakePoint(-0.81, 116.15)];
        [wavePath lineToPoint: NSMakePoint(-0.79, 116.13)];
        [wavePath curveToPoint: NSMakePoint(-0.72, 116.14) controlPoint1: NSMakePoint(-0.77, 116.14) controlPoint2: NSMakePoint(-0.75, 116.14)];
        [wavePath curveToPoint: NSMakePoint(-0.63, 116.12) controlPoint1: NSMakePoint(-0.7, 116.13) controlPoint2: NSMakePoint(-0.67, 116.13)];
        [wavePath curveToPoint: NSMakePoint(-0.56, 116.1) controlPoint1: NSMakePoint(-0.61, 116.11) controlPoint2: NSMakePoint(-0.58, 116.11)];
        [wavePath curveToPoint: NSMakePoint(-0.44, 116.06) controlPoint1: NSMakePoint(-0.52, 116.09) controlPoint2: NSMakePoint(-0.48, 116.07)];
        [wavePath curveToPoint: NSMakePoint(-0.38, 116.03) controlPoint1: NSMakePoint(-0.42, 116.05) controlPoint2: NSMakePoint(-0.4, 116.04)];
        [wavePath curveToPoint: NSMakePoint(-0.21, 115.86) controlPoint1: NSMakePoint(-0.32, 116) controlPoint2: NSMakePoint(-0.24, 115.94)];
        [wavePath curveToPoint: NSMakePoint(-0.2, 115.82) controlPoint1: NSMakePoint(-0.2, 115.85) controlPoint2: NSMakePoint(-0.2, 115.84)];
        [wavePath lineToPoint: NSMakePoint(-0.2, 115.81)];
        [wavePath lineToPoint: NSMakePoint(-0.19, 115.86)];
        [wavePath curveToPoint: NSMakePoint(-0.08, 115.99) controlPoint1: NSMakePoint(-0.17, 115.92) controlPoint2: NSMakePoint(-0.12, 115.96)];
        [wavePath curveToPoint: NSMakePoint(0.1, 116.08) controlPoint1: NSMakePoint(-0.02, 116.03) controlPoint2: NSMakePoint(0.03, 116.05)];
        [wavePath curveToPoint: NSMakePoint(0.16, 116.1) controlPoint1: NSMakePoint(0.12, 116.09) controlPoint2: NSMakePoint(0.14, 116.09)];
        [wavePath curveToPoint: NSMakePoint(0.21, 116.1) controlPoint1: NSMakePoint(0.18, 116.1) controlPoint2: NSMakePoint(0.19, 116.1)];
        [wavePath curveToPoint: NSMakePoint(0.24, 116.12) controlPoint1: NSMakePoint(0.22, 116.11) controlPoint2: NSMakePoint(0.23, 116.12)];
        [wavePath lineToPoint: NSMakePoint(0.24, 116.12)];
        [wavePath curveToPoint: NSMakePoint(0.26, 116.12) controlPoint1: NSMakePoint(0.25, 116.12) controlPoint2: NSMakePoint(0.26, 116.12)];
        [wavePath curveToPoint: NSMakePoint(0.56, 116.11) controlPoint1: NSMakePoint(0.35, 116.11) controlPoint2: NSMakePoint(0.43, 116.11)];
        [wavePath lineToPoint: NSMakePoint(0.61, 116.11)];
        [wavePath curveToPoint: NSMakePoint(0.68, 116.12) controlPoint1: NSMakePoint(0.64, 116.11) controlPoint2: NSMakePoint(0.66, 116.11)];
        [wavePath curveToPoint: NSMakePoint(1.11, 115.81) controlPoint1: NSMakePoint(0.93, 116.06) controlPoint2: NSMakePoint(1.11, 115.94)];
        [wavePath curveToPoint: NSMakePoint(1.5, 116.11) controlPoint1: NSMakePoint(1.11, 115.94) controlPoint2: NSMakePoint(1.27, 116.05)];
        [wavePath curveToPoint: NSMakePoint(1.83, 116.11) controlPoint1: NSMakePoint(1.61, 116.11) controlPoint2: NSMakePoint(1.72, 116.11)];
        [wavePath curveToPoint: NSMakePoint(2.03, 116.11) controlPoint1: NSMakePoint(1.88, 116.11) controlPoint2: NSMakePoint(1.93, 116.11)];
        [wavePath lineToPoint: NSMakePoint(2.11, 116.11)];
        [wavePath curveToPoint: NSMakePoint(2.51, 115.81) controlPoint1: NSMakePoint(2.35, 116.05) controlPoint2: NSMakePoint(2.51, 115.94)];
        [wavePath curveToPoint: NSMakePoint(2.88, 116.1) controlPoint1: NSMakePoint(2.51, 115.93) controlPoint2: NSMakePoint(2.65, 116.04)];
        [wavePath lineToPoint: NSMakePoint(2.88, 116.1)];
        [wavePath curveToPoint: NSMakePoint(3.41, 116.11) controlPoint1: NSMakePoint(3.08, 116.11) controlPoint2: NSMakePoint(3.25, 116.11)];
        [wavePath curveToPoint: NSMakePoint(3.82, 115.81) controlPoint1: NSMakePoint(3.66, 116.05) controlPoint2: NSMakePoint(3.82, 115.94)];
        [wavePath curveToPoint: NSMakePoint(4.28, 116.12) controlPoint1: NSMakePoint(3.82, 115.95) controlPoint2: NSMakePoint(4.01, 116.07)];
        [wavePath curveToPoint: NSMakePoint(4.3, 116.12) controlPoint1: NSMakePoint(4.29, 116.12) controlPoint2: NSMakePoint(4.29, 116.12)];
        [wavePath curveToPoint: NSMakePoint(4.35, 116.12) controlPoint1: NSMakePoint(4.33, 116.12) controlPoint2: NSMakePoint(4.33, 116.12)];
        [wavePath curveToPoint: NSMakePoint(4.59, 116.12) controlPoint1: NSMakePoint(4.45, 116.12) controlPoint2: NSMakePoint(4.52, 116.12)];
        [wavePath curveToPoint: NSMakePoint(4.65, 116.12) controlPoint1: NSMakePoint(4.61, 116.12) controlPoint2: NSMakePoint(4.62, 116.12)];
        [wavePath lineToPoint: NSMakePoint(4.7, 116.12)];
        [wavePath curveToPoint: NSMakePoint(4.74, 116.12) controlPoint1: NSMakePoint(4.71, 116.12) controlPoint2: NSMakePoint(4.73, 116.12)];
        [wavePath curveToPoint: NSMakePoint(5.17, 115.81) controlPoint1: NSMakePoint(5, 116.06) controlPoint2: NSMakePoint(5.17, 115.94)];
        [wavePath curveToPoint: NSMakePoint(5.53, 116.1) controlPoint1: NSMakePoint(5.17, 115.93) controlPoint2: NSMakePoint(5.31, 116.04)];
        [wavePath curveToPoint: NSMakePoint(5.78, 116.11) controlPoint1: NSMakePoint(5.61, 116.1) controlPoint2: NSMakePoint(5.7, 116.1)];
        [wavePath curveToPoint: NSMakePoint(5.95, 116.11) controlPoint1: NSMakePoint(5.87, 116.11) controlPoint2: NSMakePoint(5.9, 116.11)];
        [wavePath curveToPoint: NSMakePoint(6.16, 116.12) controlPoint1: NSMakePoint(6.02, 116.12) controlPoint2: NSMakePoint(6.09, 116.12)];
        [wavePath curveToPoint: NSMakePoint(6.58, 115.81) controlPoint1: NSMakePoint(6.41, 116.06) controlPoint2: NSMakePoint(6.58, 115.94)];
        [wavePath curveToPoint: NSMakePoint(7.06, 116.13) controlPoint1: NSMakePoint(6.58, 115.95) controlPoint2: NSMakePoint(6.78, 116.08)];
        [wavePath closePath];
        [calculatedWaveColor setFill];
        [wavePath fill];



        [NSGraphicsContext restoreGraphicsState];
    }
}

#pragma mark Generated Images

+ (NSImage*)imageOfIconWithSize: (CGFloat)size isConnected: (BOOL)isConnected isSyncInProgress: (BOOL)isSyncInProgress;
{
    return [NSImage imageWithSize: NSMakeSize(16, 16) flipped: YES drawingHandler: ^(NSRect dstRect)
    {
        [GlukloaderIcon drawIconWithSize: size isConnected: isConnected isSyncInProgress: isSyncInProgress];
        return YES;
    }];
}

@end
