//
//  GlukloaderYosemite.m
//  Glukloader
//
//  Created by Alexandre Normand on 2014-11-13.
//  Copyright (c) 2014 Glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "GlukloaderYosemite.h"


@implementation GlukloaderYosemite

#pragma mark Cache

static NSColor* _color0 = nil;

static NSImage* _imageOfGlukitIcon = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _color0 = [NSColor colorWithCalibratedRed: 0.071 green: 0.071 blue: 0.071 alpha: 1];

}

#pragma mark Colors

+ (NSColor*)color0 { return _color0; }

#pragma mark Drawing Methods

+ (void)drawGlukitIcon
{
    //// General Declarations
    CGContextRef context = (CGContextRef)NSGraphicsContext.currentContext.graphicsPort;

    //// GlukitDroplet
    {
        [NSGraphicsContext saveGraphicsState];
        CGContextTranslateCTM(context, 2.68, 0);
        CGContextScaleCTM(context, 0.1, 0.1);



        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(109.14, 57.97)];
        [bezier2Path curveToPoint: NSMakePoint(109.49, 47.18) controlPoint1: NSMakePoint(109.75, 54.4) controlPoint2: NSMakePoint(109.7, 50.78)];
        [bezier2Path curveToPoint: NSMakePoint(100.06, 20.4) controlPoint1: NSMakePoint(108.79, 37.61) controlPoint2: NSMakePoint(106, 28.14)];
        [bezier2Path curveToPoint: NSMakePoint(75.5, 3.15) controlPoint1: NSMakePoint(93.81, 12.24) controlPoint2: NSMakePoint(85.02, 6.56)];
        [bezier2Path curveToPoint: NSMakePoint(60.15, 0) controlPoint1: NSMakePoint(70.65, 1.41) controlPoint2: NSMakePoint(65.33, 0.07)];
        [bezier2Path curveToPoint: NSMakePoint(14.59, 15.06) controlPoint1: NSMakePoint(39.79, 0) controlPoint2: NSMakePoint(26.64, 2.9)];
        [bezier2Path curveToPoint: NSMakePoint(2.01, 35.81) controlPoint1: NSMakePoint(8.85, 20.83) controlPoint2: NSMakePoint(4.36, 27.94)];
        [bezier2Path curveToPoint: NSMakePoint(0.4, 57.97) controlPoint1: NSMakePoint(-0.17, 42.99) controlPoint2: NSMakePoint(-0.35, 50.55)];
        [bezier2Path lineToPoint: NSMakePoint(109.14, 57.97)];
        [bezier2Path closePath];
        [bezier2Path setMiterLimit: 4];
        [GlukloaderYosemite.color0 setFill];
        [bezier2Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path curveToPoint: NSMakePoint(78.06, 145.84) controlPoint1: NSMakePoint(76.86, 156.31) controlPoint2: NSMakePoint(77.52, 150.77)];
        [bezier4Path curveToPoint: NSMakePoint(81.87, 128.11) controlPoint1: NSMakePoint(78.78, 139.84) controlPoint2: NSMakePoint(80.24, 133.92)];
        [bezier4Path curveToPoint: NSMakePoint(90.61, 102.3) controlPoint1: NSMakePoint(84.32, 119.36) controlPoint2: NSMakePoint(87.33, 110.77)];
        [bezier4Path curveToPoint: NSMakePoint(95.63, 90.51) controlPoint1: NSMakePoint(92.15, 98.33) controlPoint2: NSMakePoint(93.71, 94.32)];
        [bezier4Path curveToPoint: NSMakePoint(108.45, 62.17) controlPoint1: NSMakePoint(100.9, 81.55) controlPoint2: NSMakePoint(104.98, 71.97)];
        [bezier4Path lineToPoint: NSMakePoint(108.43, 62.14)];
        [bezier4Path lineToPoint: NSMakePoint(108.42, 62.16)];
        [bezier4Path lineToPoint: NSMakePoint(108.38, 62.01)];
        [bezier4Path curveToPoint: NSMakePoint(108.37, 61.96) controlPoint1: NSMakePoint(108.36, 61.98) controlPoint2: NSMakePoint(108.37, 62)];
        [bezier4Path curveToPoint: NSMakePoint(108.17, 61.61) controlPoint1: NSMakePoint(108.25, 61.73) controlPoint2: NSMakePoint(108.31, 61.84)];
        [bezier4Path curveToPoint: NSMakePoint(106.22, 60.21) controlPoint1: NSMakePoint(107.73, 60.97) controlPoint2: NSMakePoint(106.92, 60.5)];
        [bezier4Path curveToPoint: NSMakePoint(99.59, 58.91) controlPoint1: NSMakePoint(104.11, 59.35) controlPoint2: NSMakePoint(101.86, 58.97)];
        [bezier4Path curveToPoint: NSMakePoint(93.37, 60.07) controlPoint1: NSMakePoint(97.48, 59.04) controlPoint2: NSMakePoint(95.35, 59.27)];
        [bezier4Path curveToPoint: NSMakePoint(90.79, 62.52) controlPoint1: NSMakePoint(92.3, 60.5) controlPoint2: NSMakePoint(90.89, 61.21)];
        [bezier4Path curveToPoint: NSMakePoint(88.83, 60.34) controlPoint1: NSMakePoint(90.72, 61.44) controlPoint2: NSMakePoint(89.71, 60.78)];
        [bezier4Path curveToPoint: NSMakePoint(82.22, 58.92) controlPoint1: NSMakePoint(86.78, 59.34) controlPoint2: NSMakePoint(84.46, 59.07)];
        [bezier4Path curveToPoint: NSMakePoint(76.21, 60.07) controlPoint1: NSMakePoint(80.18, 59.05) controlPoint2: NSMakePoint(78.12, 59.3)];
        [bezier4Path curveToPoint: NSMakePoint(73.64, 62.52) controlPoint1: NSMakePoint(75.15, 60.5) controlPoint2: NSMakePoint(73.74, 61.21)];
        [bezier4Path curveToPoint: NSMakePoint(72.21, 60.63) controlPoint1: NSMakePoint(73.58, 61.65) controlPoint2: NSMakePoint(72.91, 61.06)];
        [bezier4Path curveToPoint: NSMakePoint(65.41, 58.94) controlPoint1: NSMakePoint(70.19, 59.41) controlPoint2: NSMakePoint(67.71, 59.14)];
        [bezier4Path curveToPoint: NSMakePoint(59.76, 60.07) controlPoint1: NSMakePoint(63.5, 59.07) controlPoint2: NSMakePoint(61.55, 59.35)];
        [bezier4Path curveToPoint: NSMakePoint(57.18, 62.52) controlPoint1: NSMakePoint(58.69, 60.5) controlPoint2: NSMakePoint(57.28, 61.21)];
        [bezier4Path curveToPoint: NSMakePoint(55.75, 60.63) controlPoint1: NSMakePoint(57.12, 61.65) controlPoint2: NSMakePoint(56.45, 61.06)];
        [bezier4Path curveToPoint: NSMakePoint(49.17, 58.96) controlPoint1: NSMakePoint(53.79, 59.45) controlPoint2: NSMakePoint(51.4, 59.16)];
        [bezier4Path curveToPoint: NSMakePoint(43.73, 60.07) controlPoint1: NSMakePoint(47.33, 59.08) controlPoint2: NSMakePoint(45.45, 59.38)];
        [bezier4Path curveToPoint: NSMakePoint(41.16, 62.52) controlPoint1: NSMakePoint(42.66, 60.5) controlPoint2: NSMakePoint(41.26, 61.21)];
        [bezier4Path curveToPoint: NSMakePoint(39.19, 60.34) controlPoint1: NSMakePoint(41.08, 61.44) controlPoint2: NSMakePoint(40.07, 60.78)];
        [bezier4Path curveToPoint: NSMakePoint(32.6, 58.92) controlPoint1: NSMakePoint(37.15, 59.34) controlPoint2: NSMakePoint(34.83, 59.07)];
        [bezier4Path curveToPoint: NSMakePoint(26.62, 60.07) controlPoint1: NSMakePoint(30.57, 59.06) controlPoint2: NSMakePoint(28.52, 59.3)];
        [bezier4Path curveToPoint: NSMakePoint(24.05, 62.52) controlPoint1: NSMakePoint(25.56, 60.5) controlPoint2: NSMakePoint(24.15, 61.21)];
        [bezier4Path curveToPoint: NSMakePoint(22.62, 60.63) controlPoint1: NSMakePoint(23.99, 61.65) controlPoint2: NSMakePoint(23.32, 61.06)];
        [bezier4Path curveToPoint: NSMakePoint(16.12, 58.96) controlPoint1: NSMakePoint(20.69, 59.46) controlPoint2: NSMakePoint(18.32, 59.17)];
        [bezier4Path curveToPoint: NSMakePoint(11.75, 59.71) controlPoint1: NSMakePoint(14.65, 59.1) controlPoint2: NSMakePoint(13.17, 59.26)];
        [bezier4Path curveToPoint: NSMakePoint(9.58, 60.63) controlPoint1: NSMakePoint(10.9, 59.97) controlPoint2: NSMakePoint(10.31, 60.21)];
        [bezier4Path curveToPoint: NSMakePoint(8.26, 61.97) controlPoint1: NSMakePoint(9.05, 60.94) controlPoint2: NSMakePoint(8.5, 61.39)];
        [bezier4Path curveToPoint: NSMakePoint(8.14, 62.52) controlPoint1: NSMakePoint(8.15, 62.22) controlPoint2: NSMakePoint(8.16, 62.29)];
        [bezier4Path lineToPoint: NSMakePoint(8.13, 62.33)];
        [bezier4Path curveToPoint: NSMakePoint(8.03, 61.97) controlPoint1: NSMakePoint(8.1, 62.21) controlPoint2: NSMakePoint(8.08, 62.08)];
        [bezier4Path curveToPoint: NSMakePoint(5.88, 60.21) controlPoint1: NSMakePoint(7.68, 61.13) controlPoint2: NSMakePoint(6.66, 60.54)];
        [bezier4Path curveToPoint: NSMakePoint(5.19, 59.93) controlPoint1: NSMakePoint(5.65, 60.11) controlPoint2: NSMakePoint(5.42, 60.01)];
        [bezier4Path curveToPoint: NSMakePoint(3.76, 59.5) controlPoint1: NSMakePoint(4.71, 59.78) controlPoint2: NSMakePoint(4.24, 59.62)];
        [bezier4Path curveToPoint: NSMakePoint(2.88, 59.3) controlPoint1: NSMakePoint(3.47, 59.43) controlPoint2: NSMakePoint(3.18, 59.35)];
        [bezier4Path curveToPoint: NSMakePoint(0.95, 59.03) controlPoint1: NSMakePoint(2.24, 59.18) controlPoint2: NSMakePoint(1.6, 59.09)];
        [bezier4Path curveToPoint: NSMakePoint(10.11, 86.23) controlPoint1: NSMakePoint(2.28, 68.54) controlPoint2: NSMakePoint(5.46, 77.83)];
        [bezier4Path lineToPoint: NSMakePoint(13.51, 92.31)];
        [bezier4Path curveToPoint: NSMakePoint(80.51, 160.26) controlPoint1: NSMakePoint(31.38, 118.99) controlPoint2: NSMakePoint(55.45, 140.59)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path lineToPoint: NSMakePoint(80.51, 160.26)];
        [bezier4Path closePath];
        [bezier4Path setMiterLimit: 4];
        [GlukloaderYosemite.color0 setFill];
        [bezier4Path fill];



        [NSGraphicsContext restoreGraphicsState];
    }
}

#pragma mark Generated Images

+ (NSImage*)imageOfGlukitIcon
{
    if (_imageOfGlukitIcon)
        return _imageOfGlukitIcon;

    _imageOfGlukitIcon = [NSImage imageWithSize: NSMakeSize(16, 16) flipped: NO drawingHandler: ^(NSRect dstRect)
    {
        [GlukloaderYosemite drawGlukitIcon];

        return YES;
    }];

    return _imageOfGlukitIcon;
}

@end
